version: "2.3"
networks:
  default:
    name: itemList-dev
services:
  itemlist:
    image: ${AM_IMAGE:-item-list-dev}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DSN: 'postgresql://postgres/postgres?sslmode=disable&user=postgres&password=password'
      POSTGRES_MAX_OPEN_CONNECTIONS: 10
      POSTGRES_MAX_IDLE_CONNECTIONS: 10
      POSTGRES_CONN_MAX_LIFE_TIME: 3600
    mem_limit: 512m
    ports:
      - '4000:4000'
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: 'postgres:11.9'
    ports:
      - '5432:5432'
    hostname: postgres
    mem_limit: 1024m
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    expose:
      - "5432"